// Mocks generated by Mockito 5.4.6 from annotations
// in auto_tm/test/screens/comments/comments_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i8;

import 'package:auto_tm/domain/models/comment.dart' as _i9;
import 'package:auto_tm/domain/models/post.dart' as _i4;
import 'package:auto_tm/domain/models/post_filter.dart' as _i5;
import 'package:auto_tm/domain/repositories/post_repository.dart' as _i2;
import 'package:dio/dio.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostRepository extends _i1.Mock implements _i2.PostRepository {
  @override
  _i3.Future<List<_i4.Post>> getFeedPosts({
    required int? offset,
    required int? limit,
    _i5.PostFilter? filters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFeedPosts, [], {
              #offset: offset,
              #limit: limit,
              #filters: filters,
            }),
            returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Post>>.value(
              <_i4.Post>[],
            ),
          )
          as _i3.Future<List<_i4.Post>>);

  @override
  _i3.Future<List<_i4.Post>> getMyPosts() =>
      (super.noSuchMethod(
            Invocation.method(#getMyPosts, []),
            returnValue: _i3.Future<List<_i4.Post>>.value(<_i4.Post>[]),
            returnValueForMissingStub: _i3.Future<List<_i4.Post>>.value(
              <_i4.Post>[],
            ),
          )
          as _i3.Future<List<_i4.Post>>);

  @override
  _i3.Future<String?> createPost(Map<String, dynamic>? postData) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [postData]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<void> deletePost(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [uuid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> uploadVideo(
    String? postUuid,
    _i6.File? file, {
    void Function(int, int)? onSendProgress,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadVideo,
              [postUuid, file],
              {#onSendProgress: onSendProgress, #cancelToken: cancelToken},
            ),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> uploadPhoto(
    String? postUuid,
    _i8.Uint8List? bytes,
    int? index, {
    void Function(int, int)? onSendProgress,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadPhoto,
              [postUuid, bytes, index],
              {#onSendProgress: onSendProgress, #cancelToken: cancelToken},
            ),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<_i4.Post?> getPost(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#getPost, [uuid]),
            returnValue: _i3.Future<_i4.Post?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Post?>.value(),
          )
          as _i3.Future<_i4.Post?>);

  @override
  _i3.Future<List<_i9.Comment>> getComments(String? postUuid) =>
      (super.noSuchMethod(
            Invocation.method(#getComments, [postUuid]),
            returnValue: _i3.Future<List<_i9.Comment>>.value(<_i9.Comment>[]),
            returnValueForMissingStub: _i3.Future<List<_i9.Comment>>.value(
              <_i9.Comment>[],
            ),
          )
          as _i3.Future<List<_i9.Comment>>);

  @override
  _i3.Future<_i9.Comment?> addComment({
    required String? postUuid,
    required String? message,
    String? replyToUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addComment, [], {
              #postUuid: postUuid,
              #message: message,
              #replyToUuid: replyToUuid,
            }),
            returnValue: _i3.Future<_i9.Comment?>.value(),
            returnValueForMissingStub: _i3.Future<_i9.Comment?>.value(),
          )
          as _i3.Future<_i9.Comment?>);

  @override
  _i3.Future<void> deletePostCascade(String? postUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deletePostCascade, [postUuid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
