// Mocks generated by Mockito 5.4.6 from annotations
// in auto_tm/test/screens/search_screen/search_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:auto_tm/screens/search_screen/model/search_model.dart' as _i4;
import 'package:auto_tm/services/search_service.dart' as _i3;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRxBool_0 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SearchService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchService extends _i1.Mock implements _i3.SearchService {
  @override
  _i2.RxBool get indexReady =>
      (super.noSuchMethod(
            Invocation.getter(#indexReady),
            returnValue: _FakeRxBool_0(this, Invocation.getter(#indexReady)),
            returnValueForMissingStub: _FakeRxBool_0(
              this,
              Invocation.getter(#indexReady),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get indexBuilding =>
      (super.noSuchMethod(
            Invocation.getter(#indexBuilding),
            returnValue: _FakeRxBool_0(this, Invocation.getter(#indexBuilding)),
            returnValueForMissingStub: _FakeRxBool_0(
              this,
              Invocation.getter(#indexBuilding),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void setIndexForTesting(List<_i4.SearchModel>? data) => super.noSuchMethod(
    Invocation.method(#setIndexForTesting, [data]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i4.SearchModel>> search(
    String? query, {
    int? offset = 0,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #search,
              [query],
              {#offset: offset, #limit: limit},
            ),
            returnValue: _i5.Future<List<_i4.SearchModel>>.value(
              <_i4.SearchModel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i4.SearchModel>>.value(
              <_i4.SearchModel>[],
            ),
          )
          as _i5.Future<List<_i4.SearchModel>>);

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
