// Mocks generated by Mockito 5.4.6 from annotations
// in auto_tm/test/screens/home_screen/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i8;

import 'package:auto_tm/models/post_dtos.dart' as _i5;
import 'package:auto_tm/screens/post_details_screen/model/post_model.dart'
    as _i9;
import 'package:auto_tm/services/post_service.dart' as _i3;
import 'package:dio/dio.dart' as _i7;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PostService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostService extends _i1.Mock implements _i3.PostService {
  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.Future<String?> createPostDetails(Map<String, dynamic>? postData) =>
      (super.noSuchMethod(
            Invocation.method(#createPostDetails, [postData]),
            returnValue: _i4.Future<String?>.value(),
            returnValueForMissingStub: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<List<_i9.Post>> fetchMyPosts() =>
      (super.noSuchMethod(
            Invocation.method(#fetchMyPosts, []),
            returnValue: _i4.Future<List<_i9.Post>>.value(<_i9.Post>[]),
            returnValueForMissingStub: _i4.Future<List<_i9.Post>>.value(
              <_i9.Post>[],
            ),
          )
          as _i4.Future<List<_i9.Post>>);

  @override
  _i4.Future<void> deleteMyPost(String? uuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMyPost, [uuid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> uploadVideo(
    String? postUuid,
    _i6.File? file,
    bool? usedCompressed, {
    void Function(int, int)? onSendProgress,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadVideo,
              [postUuid, file, usedCompressed],
              {#onSendProgress: onSendProgress, #cancelToken: cancelToken},
            ),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> uploadPhoto(
    String? postUuid,
    _i8.Uint8List? bytes,
    int? index, {
    void Function(int, int)? onSendProgress,
    _i7.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadPhoto,
              [postUuid, bytes, index],
              {#onSendProgress: onSendProgress, #cancelToken: cancelToken},
            ),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> deleteCreatedPostCascade(String? postUuid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCreatedPostCascade, [postUuid]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Post>> fetchFeedPosts({
    required int? offset,
    required int? limit,
    bool? brand = true,
    bool? model = true,
    bool? photo = true,
    bool? subscription = true,
    bool? status = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFeedPosts, [], {
              #offset: offset,
              #limit: limit,
              #brand: brand,
              #model: model,
              #photo: photo,
              #subscription: subscription,
              #status: status,
            }),
            returnValue: _i4.Future<List<_i9.Post>>.value(<_i9.Post>[]),
            returnValueForMissingStub: _i4.Future<List<_i9.Post>>.value(
              <_i9.Post>[],
            ),
          )
          as _i4.Future<List<_i9.Post>>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
