// Mocks generated by Mockito 5.4.6 from annotations
// in auto_tm/test/screens/register/register_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:typed_data' as _i11;
import 'dart:ui' as _i14;

import 'package:auto_tm/screens/profile_screen/controller/profile_controller.dart'
    as _i10;
import 'package:auto_tm/screens/profile_screen/model/profile_model.dart'
    as _i12;
import 'package:auto_tm/services/auth/auth_models.dart' as _i4;
import 'package:auto_tm/services/auth/auth_service.dart' as _i3;
import 'package:auto_tm/services/notification_service/notification_service.dart'
    as _i9;
import 'package:flutter/foundation.dart' as _i7;
import 'package:flutter/material.dart' as _i6;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i13;
import 'package:get_storage/get_storage.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRx_0<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_2 extends _i1.SmartFake implements _i3.AuthService {
  _FakeAuthService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOtpSendResult_3 extends _i1.SmartFake implements _i4.OtpSendResult {
  _FakeOtpSendResult_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOtpVerifyResult_4 extends _i1.SmartFake
    implements _i4.OtpVerifyResult {
  _FakeOtpVerifyResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetStorage_5 extends _i1.SmartFake implements _i5.GetStorage {
  _FakeGetStorage_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_6 extends _i1.SmartFake
    implements _i6.TextEditingController {
  _FakeTextEditingController_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFocusNode_7 extends _i1.SmartFake implements _i6.FocusNode {
  _FakeFocusNode_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i7.DiagnosticLevel? minLevel = _i7.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeRxString_8 extends _i1.SmartFake implements _i2.RxString {
  _FakeRxString_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_9 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxn_10<T> extends _i1.SmartFake implements _i2.Rxn<T> {
  _FakeRxn_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  @override
  _i2.Rx<_i4.AuthSession?> get currentSession =>
      (super.noSuchMethod(
            Invocation.getter(#currentSession),
            returnValue: _FakeRx_0<_i4.AuthSession?>(
              this,
              Invocation.getter(#currentSession),
            ),
            returnValueForMissingStub: _FakeRx_0<_i4.AuthSession?>(
              this,
              Invocation.getter(#currentSession),
            ),
          )
          as _i2.Rx<_i4.AuthSession?>);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<_i3.AuthService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i3.AuthService>.value(
              _FakeAuthService_2(this, Invocation.method(#init, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i3.AuthService>.value(
              _FakeAuthService_2(this, Invocation.method(#init, [])),
            ),
          )
          as _i8.Future<_i3.AuthService>);

  @override
  _i8.Future<_i4.OtpSendResult> sendOtp(String? subscriberDigits) =>
      (super.noSuchMethod(
            Invocation.method(#sendOtp, [subscriberDigits]),
            returnValue: _i8.Future<_i4.OtpSendResult>.value(
              _FakeOtpSendResult_3(
                this,
                Invocation.method(#sendOtp, [subscriberDigits]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.OtpSendResult>.value(
              _FakeOtpSendResult_3(
                this,
                Invocation.method(#sendOtp, [subscriberDigits]),
              ),
            ),
          )
          as _i8.Future<_i4.OtpSendResult>);

  @override
  _i8.Future<_i4.OtpVerifyResult> verifyOtp(
    String? subscriberDigits,
    String? code,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [subscriberDigits, code]),
            returnValue: _i8.Future<_i4.OtpVerifyResult>.value(
              _FakeOtpVerifyResult_4(
                this,
                Invocation.method(#verifyOtp, [subscriberDigits, code]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i4.OtpVerifyResult>.value(
              _FakeOtpVerifyResult_4(
                this,
                Invocation.method(#verifyOtp, [subscriberDigits, code]),
              ),
            ),
          )
          as _i8.Future<_i4.OtpVerifyResult>);

  @override
  _i8.Future<_i4.AuthSession?> refreshTokens() =>
      (super.noSuchMethod(
            Invocation.method(#refreshTokens, []),
            returnValue: _i8.Future<_i4.AuthSession?>.value(),
            returnValueForMissingStub: _i8.Future<_i4.AuthSession?>.value(),
          )
          as _i8.Future<_i4.AuthSession?>);

  @override
  _i8.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i9.NotificationService {
  @override
  bool get debug =>
      (super.noSuchMethod(
            Invocation.getter(#debug),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> enableNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#enableNotifications, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> subscribeToGlobalTopic({String? topic = 'all'}) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToGlobalTopic, [], {#topic: topic}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> sendTokenToBackend(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#sendTokenToBackend, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProfileController].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileController extends _i1.Mock implements _i10.ProfileController {
  @override
  _i5.GetStorage get box =>
      (super.noSuchMethod(
            Invocation.getter(#box),
            returnValue: _FakeGetStorage_5(this, Invocation.getter(#box)),
            returnValueForMissingStub: _FakeGetStorage_5(
              this,
              Invocation.getter(#box),
            ),
          )
          as _i5.GetStorage);

  @override
  _i2.Rx<_i11.Uint8List?> get selectedImage =>
      (super.noSuchMethod(
            Invocation.getter(#selectedImage),
            returnValue: _FakeRx_0<_i11.Uint8List?>(
              this,
              Invocation.getter(#selectedImage),
            ),
            returnValueForMissingStub: _FakeRx_0<_i11.Uint8List?>(
              this,
              Invocation.getter(#selectedImage),
            ),
          )
          as _i2.Rx<_i11.Uint8List?>);

  @override
  _i6.TextEditingController get nameController =>
      (super.noSuchMethod(
            Invocation.getter(#nameController),
            returnValue: _FakeTextEditingController_6(
              this,
              Invocation.getter(#nameController),
            ),
            returnValueForMissingStub: _FakeTextEditingController_6(
              this,
              Invocation.getter(#nameController),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.TextEditingController get locationController =>
      (super.noSuchMethod(
            Invocation.getter(#locationController),
            returnValue: _FakeTextEditingController_6(
              this,
              Invocation.getter(#locationController),
            ),
            returnValueForMissingStub: _FakeTextEditingController_6(
              this,
              Invocation.getter(#locationController),
            ),
          )
          as _i6.TextEditingController);

  @override
  _i6.FocusNode get nameFocus =>
      (super.noSuchMethod(
            Invocation.getter(#nameFocus),
            returnValue: _FakeFocusNode_7(this, Invocation.getter(#nameFocus)),
            returnValueForMissingStub: _FakeFocusNode_7(
              this,
              Invocation.getter(#nameFocus),
            ),
          )
          as _i6.FocusNode);

  @override
  _i6.FocusNode get locationFocus =>
      (super.noSuchMethod(
            Invocation.getter(#locationFocus),
            returnValue: _FakeFocusNode_7(
              this,
              Invocation.getter(#locationFocus),
            ),
            returnValueForMissingStub: _FakeFocusNode_7(
              this,
              Invocation.getter(#locationFocus),
            ),
          )
          as _i6.FocusNode);

  @override
  _i2.RxString get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _FakeRxString_8(this, Invocation.getter(#name)),
            returnValueForMissingStub: _FakeRxString_8(
              this,
              Invocation.getter(#name),
            ),
          )
          as _i2.RxString);

  @override
  _i2.RxString get phone =>
      (super.noSuchMethod(
            Invocation.getter(#phone),
            returnValue: _FakeRxString_8(this, Invocation.getter(#phone)),
            returnValueForMissingStub: _FakeRxString_8(
              this,
              Invocation.getter(#phone),
            ),
          )
          as _i2.RxString);

  @override
  _i2.RxString get location =>
      (super.noSuchMethod(
            Invocation.getter(#location),
            returnValue: _FakeRxString_8(this, Invocation.getter(#location)),
            returnValueForMissingStub: _FakeRxString_8(
              this,
              Invocation.getter(#location),
            ),
          )
          as _i2.RxString);

  @override
  _i2.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_9(this, Invocation.getter(#isLoading)),
            returnValueForMissingStub: _FakeRxBool_9(
              this,
              Invocation.getter(#isLoading),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get isLoadingN =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingN),
            returnValue: _FakeRxBool_9(this, Invocation.getter(#isLoadingN)),
            returnValueForMissingStub: _FakeRxBool_9(
              this,
              Invocation.getter(#isLoadingN),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get isRefreshing =>
      (super.noSuchMethod(
            Invocation.getter(#isRefreshing),
            returnValue: _FakeRxBool_9(this, Invocation.getter(#isRefreshing)),
            returnValueForMissingStub: _FakeRxBool_9(
              this,
              Invocation.getter(#isRefreshing),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get isOffline =>
      (super.noSuchMethod(
            Invocation.getter(#isOffline),
            returnValue: _FakeRxBool_9(this, Invocation.getter(#isOffline)),
            returnValueForMissingStub: _FakeRxBool_9(
              this,
              Invocation.getter(#isOffline),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.Rxn<_i12.ProfileModel> get profile =>
      (super.noSuchMethod(
            Invocation.getter(#profile),
            returnValue: _FakeRxn_10<_i12.ProfileModel>(
              this,
              Invocation.getter(#profile),
            ),
            returnValueForMissingStub: _FakeRxn_10<_i12.ProfileModel>(
              this,
              Invocation.getter(#profile),
            ),
          )
          as _i2.Rxn<_i12.ProfileModel>);

  @override
  _i2.RxBool get fieldsInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#fieldsInitialized),
            returnValue: _FakeRxBool_9(
              this,
              Invocation.getter(#fieldsInitialized),
            ),
            returnValueForMissingStub: _FakeRxBool_9(
              this,
              Invocation.getter(#fieldsInitialized),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get isFetchingProfile =>
      (super.noSuchMethod(
            Invocation.getter(#isFetchingProfile),
            returnValue: _FakeRxBool_9(
              this,
              Invocation.getter(#isFetchingProfile),
            ),
            returnValueForMissingStub: _FakeRxBool_9(
              this,
              Invocation.getter(#isFetchingProfile),
            ),
          )
          as _i2.RxBool);

  @override
  _i2.RxBool get hasLoadedProfile =>
      (super.noSuchMethod(
            Invocation.getter(#hasLoadedProfile),
            returnValue: _FakeRxBool_9(
              this,
              Invocation.getter(#hasLoadedProfile),
            ),
            returnValueForMissingStub: _FakeRxBool_9(
              this,
              Invocation.getter(#hasLoadedProfile),
            ),
          )
          as _i2.RxBool);

  @override
  set selectedImage(_i2.Rx<_i11.Uint8List?>? value) => super.noSuchMethod(
    Invocation.setter(#selectedImage, value),
    returnValueForMissingStub: null,
  );

  @override
  set name(_i2.RxString? value) => super.noSuchMethod(
    Invocation.setter(#name, value),
    returnValueForMissingStub: null,
  );

  @override
  set phone(_i2.RxString? value) => super.noSuchMethod(
    Invocation.setter(#phone, value),
    returnValueForMissingStub: null,
  );

  @override
  set location(_i2.RxString? value) => super.noSuchMethod(
    Invocation.setter(#location, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoading(_i2.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoading, value),
    returnValueForMissingStub: null,
  );

  @override
  set isLoadingN(_i2.RxBool? value) => super.noSuchMethod(
    Invocation.setter(#isLoadingN, value),
    returnValueForMissingStub: null,
  );

  @override
  set profile(_i2.Rxn<_i12.ProfileModel>? value) => super.noSuchMethod(
    Invocation.setter(#profile, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
            returnValueForMissingStub: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(
            Invocation.getter(#initialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(
            Invocation.getter(#listeners),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  void debugDumpFlags(String? label) => super.noSuchMethod(
    Invocation.method(#debugDumpFlags, [label]),
    returnValueForMissingStub: null,
  );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> testApiConnection() =>
      (super.noSuchMethod(
            Invocation.method(#testApiConnection, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> testJsonParsing(String? jsonString) =>
      (super.noSuchMethod(
            Invocation.method(#testJsonParsing, [jsonString]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchProfile({bool? retry = false}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfile, [], {#retry: retry}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> waitForInitialLoad({
    Duration? timeout = const Duration(seconds: 6),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#waitForInitialLoad, [], {#timeout: timeout}),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchProfileAndPopulateFields() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProfileAndPopulateFields, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void ensureFormFieldPrefill({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#ensureFormFieldPrefill, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> requestGalleryPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestGalleryPermission, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> pickImage() =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> uploadImage(_i11.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [imageBytes]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> uploadProfile() =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfile, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> postUserDataSave() =>
      (super.noSuchMethod(
            Invocation.method(#postUserDataSave, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void logout() => super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValueForMissingStub: null,
  );

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListener(_i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i13.Disposer);

  @override
  void removeListener(_i14.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i14.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i13.Disposer addListenerId(Object? key, _i13.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i13.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
